version: "3.8"
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - type: volume
        source: neo4jdata
        target: /data
      - type: volume
        source: neo4jimport
        target: /var/lib/neo4j/import

  pulumigraph:
    build:
      context: ./docker
    image: pulumigraph
    depends_on:
      - neo4j
    entrypoint: [ "/bin/bash" ]
    environment:
      - PULUMI_ACCESS_TOKEN
    command: [ "./wait-for-it.sh", "-t", "30", "neo4j:7474", "--", "./.dotnet/tools/pulumigraph", "-h", "neo4j" ]

## For debugging the pulumigraph container
  # shell:
  #   build:
  #     context: ./docker
  #   image: pulumigraph
  #   depends_on:
  #     - neo4j
  #   entrypoint: [ "/bin/bash" ]
  #   environment:
  #     - PULUMI_ACCESS_TOKEN

volumes:
  neo4jdata:
  neo4jimport:
